# This workflow runs the repo's CI tests.
name: CI

on:
  push:
    branches: [main, v1]
  pull_request:
    branches: [main, v1]
  schedule:
    - cron: 0 4 * * 1  # every monday at 04:00 UTC
  workflow_dispatch:

jobs:
  ci:
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          create-args: python=${{ matrix.python-version }}
          environment-file: ./environments/tests/env-ci.yml
          post-cleanup: none

      - name: Install OSMnx
        run: |
          python -m pip install .
          python -m pip check
          micromamba list
          python -m pip show osmnx

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit checks
        run: pre-commit run --all-files
        env:
          SKIP: no-commit-to-branch

      - name: Build and check package
        run: |
          python -m validate_pyproject ./pyproject.toml
          python -m hatch build --clean
          python -m twine check --strict ./dist/*

      - name: Test docs build
        run: python -m sphinx -E -W --keep-going -b html ./docs/source ./docs/build/html

      - name: Test code and coverage
        run: >
             python -m pytest
             --verbose
             --maxfail=1
             --typeguard-packages=osmnx
             --cov=osmnx
             --cov-report=xml
             --numprocesses=3
             --dist=loadgroup

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
