# This workflow tests building the package docs and verifying links are live.
name: Build docs and check links

on:
  schedule:
    - cron: 10 4 * * 1  # every monday at 04:10 UTC
  workflow_dispatch:

jobs:
  test_docs_linkcheck:
    if: ${{ github.repository == 'gboeing/osmnx' }}
    name: Build docs and check links
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        shell: bash -elo pipefail {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.*
          cache: pip
          cache-dependency-path: ./environments/requirements/requirements-docs.txt

      - name: Install requirements
        run: |
          python -m pip install -r ./environments/requirements/requirements-docs.txt
          python -m pip check

      - name: Build docs and check links
        run: python -m sphinx -E -W --keep-going -b linkcheck ./docs/source ./docs/build/linkcheck
